### PR TITLE
Voronoi take 4

### PR DESCRIPTION
**Pull request by bluescarni**
New version of the voronoi grid support using voro++ as a backend. Performance is better than qhull, but there are still adaptations to be done on the Fortran side.

### CODE REVIEW

**Comment by bluescarni** [comment]
@astrofrog I have found another issue in the code after debugging. It turns out that voro++ does not work well if a site is exactly on the domain wall, so I changed the logic in voronoi_grid.py to add a bit of padding to the auto-detected domain walls.

Now the test model runs ok, it produces what looks like a cube filled with white noise :)

**Comment by astrofrog** [comment]
@bluescarni - great, thanks for figuring it out! I will review and merge if there are no issues :)

**Comment by astrofrog** [comment]
@bluescarni - this looks good! Two small things:
- Could you add an entry to `docs/changes.rst`?
- Could you add a test to `test_model.py` based on the small example of the cube I showed you? You can do something similar to https://github.com/hyperion-rt/hyperion/blob/master/hyperion/model/tests/test_model.py#L279 to basically just check that the model runs. This actually checks the C code, the Python wrapping code, and the Fortran code in the runner. No need to check the output itself for now, already checking that it runs would be great. Try reducing the number of photons until the total time for set-up and running is ~10s at most.

Once this is done, we can merge!

**Comment by bluescarni** [comment]
@astrofrog sure, I am on it.

**Comment by bluescarni** [comment]
@astrofrog I added the changes to the doc file, and added a test model based on the one you sent me.

I also added some additional testing for checking that the results of the new voro++ code are consistent with the old qhull-based code on 3 random grids, and docs in the helpers as well.

**Comment by astrofrog** [comment]
@bluescarni - great, thanks for doing this! I'll merge this now and will see if the tests pass in the main pull request.

**Pull request merged**
